# Generated by Django 5.2.8 on 2025-12-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(default='Etc', max_length=50),
        ),
    ]
